import type { Metadata } from "next";
import { DashboardHeader } from "@/components/dashboard/component";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <DashboardHeader />
      {children}
    </main>
  );
}
